OTHER_FILES += \
   src/chunkserver/chunkserver.conf.template \
   src/chunkserver/Makefile.am \
   src/clustermanager/Makefile.am \
   src/clustermanager/ocm.conf.template \
   src/common/btree/test/Makefile.am \
   src/common/cmbtree/SConstruct \
   src/common/compress/Makefile.am \
   src/common/roottable/Makefile.am \
   src/common/timezone/Makefile.am

HEADERS += \
   src/chunkserver/ob_block_cache_loader.h \
   src/chunkserver/ob_block_cache_reader.h \
   src/chunkserver/ob_bypass_sstable_loader.h \
   src/chunkserver/ob_cell_array_helper.h \
   src/chunkserver/ob_cell_stream.h \
   src/chunkserver/ob_chunk_callback.h \
   src/chunkserver/ob_chunk_merge.h \
   src/chunkserver/ob_chunk_reload_config.h \
   src/chunkserver/ob_chunk_server_config.h \
   src/chunkserver/ob_chunk_server_main.h \
   src/chunkserver/ob_chunk_server_merger_proxy.h \
   src/chunkserver/ob_chunk_server_stat.h \
   src/chunkserver/ob_chunk_server.h \
   src/chunkserver/ob_chunk_service.h \
   src/chunkserver/ob_compactsstable_cache.h \
   src/chunkserver/ob_disk_manager.h \
   src/chunkserver/ob_file_recycle.h \
   src/chunkserver/ob_fileinfo_cache.h \
   src/chunkserver/ob_get_cell_stream_wrapper.h \
   src/chunkserver/ob_get_cell_stream.h \
   src/chunkserver/ob_get_param_cell_iterator.h \
   src/chunkserver/ob_get_scan_proxy.h \
   src/chunkserver/ob_join_cache.h \
   src/chunkserver/ob_join_operator.h \
   src/chunkserver/ob_merge_join_operator.h \
   src/chunkserver/ob_merge_operator.h \
   src/chunkserver/ob_merge_reader.h \
   src/chunkserver/ob_multi_tablet_merger.h \
   src/chunkserver/ob_query_agent.h \
   src/chunkserver/ob_query_service.h \
   src/chunkserver/ob_read_param_modifier.h \
   src/chunkserver/ob_read_ups_balance.h \
   src/chunkserver/ob_root_server_rpc.h \
   src/chunkserver/ob_row_cell_vec.h \
   src/chunkserver/ob_rpc_proxy.h \
   src/chunkserver/ob_scan_cell_stream.h \
   src/chunkserver/ob_schema_manager.h \
   src/chunkserver/ob_schema_task.h \
   src/chunkserver/ob_sql_query_service.h \
   src/chunkserver/ob_sql_rpc_stub.h \
   src/chunkserver/ob_switch_cache_utility.h \
   src/chunkserver/ob_tablet_image.h \
   src/chunkserver/ob_tablet_manager.h \
   src/chunkserver/ob_tablet_merge_filter.h \
   src/chunkserver/ob_tablet_merger_v1.h \
   src/chunkserver/ob_tablet_merger_v2.h \
   src/chunkserver/ob_tablet_reader.h \
   src/chunkserver/ob_tablet_service.h \
   src/chunkserver/ob_tablet_writer.h \
   src/chunkserver/ob_tablet.h \
   src/chunkserver/ob_ups_blacklist.h \
   src/clustermanager/ob_ocm_app_info.h \
   src/clustermanager/ob_ocm_broadcast_task.h \
   src/clustermanager/ob_ocm_instance.h \
   src/clustermanager/ob_ocm_main.h \
   src/clustermanager/ob_ocm_meta_manager.h \
   src/clustermanager/ob_ocm_meta.h \
   src/clustermanager/ob_ocm_param.h \
   src/clustermanager/ob_ocm_rpc_stub.h \
   src/clustermanager/ob_ocm_server.h \
   src/clustermanager/ob_ocm_service.h \
   src/common/btree/test/test_key_str.h \
   src/common/btree/test/test_key_zl.h \
   src/common/btree/test/test_key.h \
   src/common/cmbtree/btree_base.h \
   src/common/cmbtree/btree_counter.h \
   src/common/cmbtree/btree_default_alloc.h \
   src/common/cmbtree/btree_define.h \
   src/common/cmbtree/btree_handle.h \
   src/common/cmbtree/btree_mem_pool.h \
   src/common/cmbtree/btree_mutex.h \
   src/common/cmbtree/btree_node.h \
   src/common/cmbtree/btree_read_param.h \
   src/common/cmbtree/btree_recycle_node.h \
   src/common/cmbtree/btree_recycle_pool.h \
   src/common/cmbtree/btree_thread_store.h \
   src/common/cmbtree/btree_tid.h \
   src/common/cmbtree/btree_write_param.h \
   src/common/cmbtree/qlock.h \
   src/common/cmbtree/thread.h \
   src/common/compress/lzo_compressor.h \
   src/common/compress/none_compressor.h \
   src/common/compress/ob_compressor.h \
   src/common/compress/snappy_compressor.h \
   src/common/hash/ob_hashmap.h \
   src/common/hash/ob_hashset.h \
   src/common/hash/ob_hashtable.h \
   src/common/hash/ob_hashutils.h \
   src/common/hash/ob_placement_hashmap.h \
   src/common/hash/ob_placement_hashset.h \
   src/common/hash/ob_serialization.h \
   src/common/location/ob_btree_map.h \
   src/common/location/ob_ms_cache_table.h \
   src/common/location/ob_tablet_location_cache_proxy.h \
   src/common/location/ob_tablet_location_cache.h \
   src/common/location/ob_tablet_location_list.h \
   src/common/location/ob_tablet_location_range_iterator.h \
   src/common/nb_accessor/nb_query_res.h \
   src/common/nb_accessor/nb_scan_cond.h \
   src/common/nb_accessor/nb_table_row.h \
   src/common/nb_accessor/ob_nb_accessor.h \
   src/common/roottable/ob_first_tablet_entry_meta.h \
   src/common/roottable/ob_first_tablet_entry_schema.h \
   src/common/roottable/ob_first_tablet_entry.h \
   src/common/roottable/ob_meta_table_schema.h \
   src/common/roottable/ob_meta_table3.h \
   src/common/roottable/ob_ms_provider.h \
   src/common/roottable/ob_mutate_helper.h \
   src/common/roottable/ob_old_root_table_schema.h \
   src/common/roottable/ob_root_table_service.h \
   src/common/roottable/ob_root_table3.h \
   src/common/roottable/ob_scan_helper_impl.h \
   src/common/roottable/ob_scan_helper.h \
   src/common/roottable/ob_tablet_meta_table_row.h \
   src/common/roottable/ob_tablet_meta_table.h \
   src/common/roottable/ob_ups_provider.h \
   src/common/timezone/private.h \
   src/common/timezone/tzfile.h

SOURCES += \
   src/chunkserver/main.cpp \
   src/chunkserver/ob_block_cache_loader.cpp \
   src/chunkserver/ob_block_cache_reader.cpp \
   src/chunkserver/ob_bypass_sstable_loader.cpp \
   src/chunkserver/ob_cell_array_helper.cpp \
   src/chunkserver/ob_cell_stream.cpp \
   src/chunkserver/ob_chunk_callback.cpp \
   src/chunkserver/ob_chunk_merge.cpp \
   src/chunkserver/ob_chunk_reload_config.cpp \
   src/chunkserver/ob_chunk_server_config.cpp \
   src/chunkserver/ob_chunk_server_main.cpp \
   src/chunkserver/ob_chunk_server_merger_proxy.cpp \
   src/chunkserver/ob_chunk_server_stat.cpp \
   src/chunkserver/ob_chunk_server.cpp \
   src/chunkserver/ob_chunk_service.cpp \
   src/chunkserver/ob_compactsstable_cache.cpp \
   src/chunkserver/ob_disk_manager.cpp \
   src/chunkserver/ob_disk_path.cpp \
   src/chunkserver/ob_file_recycle.cpp \
   src/chunkserver/ob_fileinfo_cache.cpp \
   src/chunkserver/ob_get_cell_stream_wrapper.cpp \
   src/chunkserver/ob_get_cell_stream.cpp \
   src/chunkserver/ob_get_param_cell_iterator.cpp \
   src/chunkserver/ob_get_scan_proxy.cpp \
   src/chunkserver/ob_join_cache.cpp \
   src/chunkserver/ob_join_operator.cpp \
   src/chunkserver/ob_merge_join_operator.cpp \
   src/chunkserver/ob_merge_operator.cpp \
   src/chunkserver/ob_merge_reader.cpp \
   src/chunkserver/ob_multi_tablet_merger.cpp \
   src/chunkserver/ob_query_agent.cpp \
   src/chunkserver/ob_query_service.cpp \
   src/chunkserver/ob_read_param_modifier.cpp \
   src/chunkserver/ob_read_ups_balance.cpp \
   src/chunkserver/ob_root_server_rpc.cpp \
   src/chunkserver/ob_row_cell_vec.cpp \
   src/chunkserver/ob_rpc_proxy.cpp \
   src/chunkserver/ob_scan_cell_stream.cpp \
   src/chunkserver/ob_schema_manager.cpp \
   src/chunkserver/ob_schema_task.cpp \
   src/chunkserver/ob_sql_rpc_stub.cpp \
   src/chunkserver/ob_switch_cache_utility.cpp \
   src/chunkserver/ob_tablet_image.cpp \
   src/chunkserver/ob_tablet_manager.cpp \
   src/chunkserver/ob_tablet_merge_filter.cpp \
   src/chunkserver/ob_tablet_merger_v1.cpp \
   src/chunkserver/ob_tablet_merger_v2.cpp \
   src/chunkserver/ob_tablet_reader.cpp \
   src/chunkserver/ob_tablet_service.cpp \
   src/chunkserver/ob_tablet_writer.cpp \
   src/chunkserver/ob_tablet.cpp \
   src/chunkserver/ob_ups_blacklist.cpp \
   src/clustermanager/ob_ocm_app_info.cpp \
   src/clustermanager/ob_ocm_broadcast_task.cpp \
   src/clustermanager/ob_ocm_instance.cpp \
   src/clustermanager/ob_ocm_main.cpp \
   src/clustermanager/ob_ocm_meta_manager.cpp \
   src/clustermanager/ob_ocm_meta.cpp \
   src/clustermanager/ob_ocm_param.cpp \
   src/clustermanager/ob_ocm_rpc_stub.cpp \
   src/clustermanager/ob_ocm_server.cpp \
   src/clustermanager/ob_ocm_service.cpp \
   src/clustermanager/ocm_admin.cpp \
   src/common/btree/test/btree_alloc_test.cpp \
   src/common/btree/test/btree_base_test.cpp \
   src/common/btree/test/btree_node_test.cpp \
   src/common/btree/test/btree_read_handle_test.cpp \
   src/common/btree/test/btree_root_pointer_test.cpp \
   src/common/btree/test/btree_test.cpp \
   src/common/btree/test/btree_write_handle_test.cpp \
   src/common/btree/test/key_btree_mthread.cpp \
   src/common/btree/test/key_btree_test.cpp \
   src/common/btree/test/keytree_get_test.cpp \
   src/common/btree/test/keytree_getnext_test.cpp \
   src/common/btree/test/keytree_put_test.cpp \
   src/common/btree/test/keytree_remove_test.cpp \
   src/common/btree/test/test_batch.cpp \
   src/common/* \
   src/common/cmbtree/test.cpp \
   src/common/cmbtree/test1.cpp \
   src/common/cmbtree/test2.cpp \
   src/common/cmbtree/test3.cpp \
   src/common/cmbtree/test4.cpp \
   src/common/compress/lzo_compressor.cpp \
   src/common/compress/none_compressor.cpp \
   src/common/compress/ob_compressor.cpp \
   src/common/compress/snappy_compressor.cpp \
   src/common/location/ob_tablet_location_cache_proxy.cpp \
   src/common/location/ob_tablet_location_cache.cpp \
   src/common/location/ob_tablet_location_list.cpp \
   src/common/location/ob_tablet_location_range_iterator.cpp \
   src/common/nb_accessor/nb_query_res.cpp \
   src/common/nb_accessor/nb_scan_cond.cpp \
   src/common/nb_accessor/nb_table_row.cpp \
   src/common/nb_accessor/ob_nb_accessor.cpp \
   src/common/roottable/ob_first_tablet_entry_meta.cpp \
   src/common/roottable/ob_first_tablet_entry_schema.cpp \
   src/common/roottable/ob_first_tablet_entry.cpp \
   src/common/roottable/ob_meta_table_schema.cpp \
   src/common/roottable/ob_meta_table3.cpp \
   src/common/roottable/ob_old_root_table_schema.cpp \
   src/common/roottable/ob_root_table_service.cpp \
   src/common/roottable/ob_root_table3.cpp \
   src/common/roottable/ob_scan_helper_impl.cpp \
   src/common/roottable/ob_tablet_meta_table_row.cpp \
   src/common/timezone/localtime.c

