OTHER_FILES += \
   src/chunkserver/chunkserver.conf.template \
   src/chunkserver/Makefile.am \
   src/clustermanager/Makefile.am \
   src/clustermanager/ocm.conf.template \
   src/common/btree/test/Makefile.am \
   src/common/cmbtree/SConstruct \
   src/common/compress/Makefile.am \
   src/common/roottable/Makefile.am \
   src/common/timezone/Makefile.am \
    src/mergeserver/Makefile.am \
    src/mergeserver/mergeserver.conf.template \
    src/rootserver/Flymake.mk \
    src/rootserver/Makefile.am \
    src/rootserver/rootserver.conf.template \
    src/rootserver/meta_table_schema.ini \
    src/rootserver/schema.ini \
    src/rootserver/test1.ini \
    src/proxyserver/Makefile.am \
    src/proxyserver/proxyserver.conf.template \
    src/updateserver/Makefile.am \
    src/updateserver/updateserver.conf.template \
    src/compactsstable/Makefile.am

HEADERS += \
   src/chunkserver/ob_block_cache_loader.h \
   src/chunkserver/ob_block_cache_reader.h \
   src/chunkserver/ob_bypass_sstable_loader.h \
   src/chunkserver/ob_cell_array_helper.h \
   src/chunkserver/ob_cell_stream.h \
   src/chunkserver/ob_chunk_callback.h \
   src/chunkserver/ob_chunk_merge.h \
   src/chunkserver/ob_chunk_reload_config.h \
   src/chunkserver/ob_chunk_server_config.h \
   src/chunkserver/ob_chunk_server_main.h \
   src/chunkserver/ob_chunk_server_merger_proxy.h \
   src/chunkserver/ob_chunk_server_stat.h \
   src/chunkserver/ob_chunk_server.h \
   src/chunkserver/ob_chunk_service.h \
   src/chunkserver/ob_compactsstable_cache.h \
   src/chunkserver/ob_disk_manager.h \
   src/chunkserver/ob_file_recycle.h \
   src/chunkserver/ob_fileinfo_cache.h \
   src/chunkserver/ob_get_cell_stream_wrapper.h \
   src/chunkserver/ob_get_cell_stream.h \
   src/chunkserver/ob_get_param_cell_iterator.h \
   src/chunkserver/ob_get_scan_proxy.h \
   src/chunkserver/ob_join_cache.h \
   src/chunkserver/ob_join_operator.h \
   src/chunkserver/ob_merge_join_operator.h \
   src/chunkserver/ob_merge_operator.h \
   src/chunkserver/ob_merge_reader.h \
   src/chunkserver/ob_multi_tablet_merger.h \
   src/chunkserver/ob_query_agent.h \
   src/chunkserver/ob_query_service.h \
   src/chunkserver/ob_read_param_modifier.h \
   src/chunkserver/ob_read_ups_balance.h \
   src/chunkserver/ob_root_server_rpc.h \
   src/chunkserver/ob_row_cell_vec.h \
   src/chunkserver/ob_rpc_proxy.h \
   src/chunkserver/ob_scan_cell_stream.h \
   src/chunkserver/ob_schema_manager.h \
   src/chunkserver/ob_schema_task.h \
   src/chunkserver/ob_sql_query_service.h \
   src/chunkserver/ob_sql_rpc_stub.h \
   src/chunkserver/ob_switch_cache_utility.h \
   src/chunkserver/ob_tablet_image.h \
   src/chunkserver/ob_tablet_manager.h \
   src/chunkserver/ob_tablet_merge_filter.h \
   src/chunkserver/ob_tablet_merger_v1.h \
   src/chunkserver/ob_tablet_merger_v2.h \
   src/chunkserver/ob_tablet_reader.h \
   src/chunkserver/ob_tablet_service.h \
   src/chunkserver/ob_tablet_writer.h \
   src/chunkserver/ob_tablet.h \
   src/chunkserver/ob_ups_blacklist.h \
   src/clustermanager/ob_ocm_app_info.h \
   src/clustermanager/ob_ocm_broadcast_task.h \
   src/clustermanager/ob_ocm_instance.h \
   src/clustermanager/ob_ocm_main.h \
   src/clustermanager/ob_ocm_meta_manager.h \
   src/clustermanager/ob_ocm_meta.h \
   src/clustermanager/ob_ocm_param.h \
   src/clustermanager/ob_ocm_rpc_stub.h \
   src/clustermanager/ob_ocm_server.h \
   src/clustermanager/ob_ocm_service.h \
   src/common/btree/test/test_key_str.h \
   src/common/btree/test/test_key_zl.h \
   src/common/btree/test/test_key.h \
   src/common/cmbtree/btree_base.h \
   src/common/cmbtree/btree_counter.h \
   src/common/cmbtree/btree_default_alloc.h \
   src/common/cmbtree/btree_define.h \
   src/common/cmbtree/btree_handle.h \
   src/common/cmbtree/btree_mem_pool.h \
   src/common/cmbtree/btree_mutex.h \
   src/common/cmbtree/btree_node.h \
   src/common/cmbtree/btree_read_param.h \
   src/common/cmbtree/btree_recycle_node.h \
   src/common/cmbtree/btree_recycle_pool.h \
   src/common/cmbtree/btree_thread_store.h \
   src/common/cmbtree/btree_tid.h \
   src/common/cmbtree/btree_write_param.h \
   src/common/cmbtree/qlock.h \
   src/common/cmbtree/thread.h \
   src/common/compress/lzo_compressor.h \
   src/common/compress/none_compressor.h \
   src/common/compress/ob_compressor.h \
   src/common/compress/snappy_compressor.h \
   src/common/hash/ob_hashmap.h \
   src/common/hash/ob_hashset.h \
   src/common/hash/ob_hashtable.h \
   src/common/hash/ob_hashutils.h \
   src/common/hash/ob_placement_hashmap.h \
   src/common/hash/ob_placement_hashset.h \
   src/common/hash/ob_serialization.h \
   src/common/location/ob_btree_map.h \
   src/common/location/ob_ms_cache_table.h \
   src/common/location/ob_tablet_location_cache_proxy.h \
   src/common/location/ob_tablet_location_cache.h \
   src/common/location/ob_tablet_location_list.h \
   src/common/location/ob_tablet_location_range_iterator.h \
   src/common/nb_accessor/nb_query_res.h \
   src/common/nb_accessor/nb_scan_cond.h \
   src/common/nb_accessor/nb_table_row.h \
   src/common/nb_accessor/ob_nb_accessor.h \
   src/common/roottable/ob_first_tablet_entry_meta.h \
   src/common/roottable/ob_first_tablet_entry_schema.h \
   src/common/roottable/ob_first_tablet_entry.h \
   src/common/roottable/ob_meta_table_schema.h \
   src/common/roottable/ob_meta_table3.h \
   src/common/roottable/ob_ms_provider.h \
   src/common/roottable/ob_mutate_helper.h \
   src/common/roottable/ob_old_root_table_schema.h \
   src/common/roottable/ob_root_table_service.h \
   src/common/roottable/ob_root_table3.h \
   src/common/roottable/ob_scan_helper_impl.h \
   src/common/roottable/ob_scan_helper.h \
   src/common/roottable/ob_tablet_meta_table_row.h \
   src/common/roottable/ob_tablet_meta_table.h \
   src/common/roottable/ob_ups_provider.h \
   src/common/timezone/private.h \
   src/common/timezone/tzfile.h \
    src/mergeserver/ob_bloom_filter_task_queue_thread.h \
    src/mergeserver/ob_chunk_server_task_dispatcher.h \
    src/mergeserver/ob_frozen_data_cache.h \
    src/mergeserver/ob_get_privilege_task.h \
    src/mergeserver/ob_insert_cache.h \
    src/mergeserver/ob_merge_callback.h \
    src/mergeserver/ob_merge_reload_config.h \
    src/mergeserver/ob_merge_server_config.h \
    src/mergeserver/ob_merge_server_main.h \
    src/mergeserver/ob_merge_server_service.h \
    src/mergeserver/ob_merge_server.h \
    src/mergeserver/ob_merger_groupby_operator.h \
    src/mergeserver/ob_merger_operator.h \
    src/mergeserver/ob_merger_reverse_operator.h \
    src/mergeserver/ob_merger_sorted_operator.h \
    src/mergeserver/ob_ms_async_rpc.h \
    src/mergeserver/ob_ms_dump_util.h \
    src/mergeserver/ob_ms_get_request.h \
    src/mergeserver/ob_ms_lease_task.h \
    src/mergeserver/ob_ms_monitor_task.h \
    src/mergeserver/ob_ms_request.h \
    src/mergeserver/ob_ms_rpc_event.h \
    src/mergeserver/ob_ms_rpc_proxy.h \
    src/mergeserver/ob_ms_scan_param.h \
    src/mergeserver/ob_ms_scan_request.h \
    src/mergeserver/ob_ms_scanner_encoder.h \
    src/mergeserver/ob_ms_schema_proxy.h \
    src/mergeserver/ob_ms_schema_task.h \
    src/mergeserver/ob_ms_server_counter.h \
    src/mergeserver/ob_ms_service_monitor.h \
    src/mergeserver/ob_ms_sql_get_request.h \
    src/mergeserver/ob_ms_sql_operator.h \
    src/mergeserver/ob_ms_sql_proxy.h \
    src/mergeserver/ob_ms_sql_request.h \
    src/mergeserver/ob_ms_sql_rpc_event.h \
    src/mergeserver/ob_ms_sql_scan_request.h \
    src/mergeserver/ob_ms_sql_sorted_operator.h \
    src/mergeserver/ob_ms_sql_sub_get_request.h \
    src/mergeserver/ob_ms_sql_sub_scan_request.h \
    src/mergeserver/ob_ms_sub_get_request.h \
    src/mergeserver/ob_ms_sub_scan_request.h \
    src/mergeserver/ob_ms_tsi.h \
    src/mergeserver/ob_ms_ups_task.h \
    src/mergeserver/ob_mutator_param_decoder.h \
    src/mergeserver/ob_param_decoder.h \
    src/mergeserver/ob_query_cache.h \
    src/mergeserver/ob_read_param_decoder.h \
    src/mergeserver/ob_read_param_modifier.h \
    src/mergeserver/ob_rpc_event.h \
    src/mergeserver/ob_rs_rpc_proxy.h \
    src/mergeserver/ob_sql_rpc_event.h \
    src/rootserver/ob_chunk_server_manager.h \
    src/rootserver/ob_daily_merge_checker.h \
    src/rootserver/ob_data_source_mgr.h \
    src/rootserver/ob_heartbeat_checker.h \
    src/rootserver/ob_migrate_info.h \
    src/rootserver/ob_restart_server.h \
    src/rootserver/ob_root_admin_cmd.h \
    src/rootserver/ob_root_admin2.h \
    src/rootserver/ob_root_async_task_queue.h \
    src/rootserver/ob_root_balancer_runnable.h \
    src/rootserver/ob_root_balancer.h \
    src/rootserver/ob_root_bootstrap.h \
    src/rootserver/ob_root_callback.h \
    src/rootserver/ob_root_ddl_operator.h \
    src/rootserver/ob_root_fetch_thread.h \
    src/rootserver/ob_root_inner_table_task.h \
    src/rootserver/ob_root_log_manager.h \
    src/rootserver/ob_root_log_replay.h \
    src/rootserver/ob_root_log_worker.h \
    src/rootserver/ob_root_main.h \
    src/rootserver/ob_root_meta2.h \
    src/rootserver/ob_root_monitor_table.h \
    src/rootserver/ob_root_ms_provider.h \
    src/rootserver/ob_root_operation_data.h \
    src/rootserver/ob_root_operation_helper.h \
    src/rootserver/ob_root_reload_config.h \
    src/rootserver/ob_root_rpc_stub.h \
    src/rootserver/ob_root_server_config.h \
    src/rootserver/ob_root_server_state.h \
    src/rootserver/ob_root_server2.h \
    src/rootserver/ob_root_sql_proxy.h \
    src/rootserver/ob_root_stat_key.h \
    src/rootserver/ob_root_stat.h \
    src/rootserver/ob_root_table_operation.h \
    src/rootserver/ob_root_table2.h \
    src/rootserver/ob_root_timer_task.h \
    src/rootserver/ob_root_ups_provider.h \
    src/rootserver/ob_root_util.h \
    src/rootserver/ob_root_worker.h \
    src/rootserver/ob_rs_after_restart_task.h \
    src/rootserver/ob_rs_schema_operation.h \
    src/rootserver/ob_rs_trigger_event_util.h \
    src/rootserver/ob_schema_service_ms_provider.h \
    src/rootserver/ob_schema_service_ups_provider.h \
    src/rootserver/ob_server_balance_info.h \
    src/rootserver/ob_tablet_info_manager.h \
    src/rootserver/ob_ups_check_runnable.h \
    src/rootserver/ob_ups_heartbeat_runnable.h \
    src/rootserver/ob_ups_manager.h \
    src/proxyserver/ob_proxy_callback.h \
    src/proxyserver/ob_proxy_reader.h \
    src/proxyserver/ob_proxy_server_config.h \
    src/proxyserver/ob_proxy_server_main.h \
    src/proxyserver/ob_proxy_server.h \
    src/proxyserver/ob_proxy_service.h \
    src/proxyserver/ob_yunti_meta.h \
    src/proxyserver/ob_yunti_proxy.h \
    src/updateserver/ob_async_log_applier.h \
    src/updateserver/ob_atomic.h \
    src/updateserver/ob_bit_lock.h \
    src/updateserver/ob_btree_engine_alloc.h \
    src/updateserver/ob_btree_engine.h \
    src/updateserver/ob_cached_pos_log_reader.h \
    src/updateserver/ob_client_wrapper_tsi.h \
    src/updateserver/ob_client_wrapper.h \
    src/updateserver/ob_clog_stat.h \
    src/updateserver/ob_commit_log_receiver.h \
    src/updateserver/ob_data_block.h \
    src/updateserver/ob_fetched_log.h \
    src/updateserver/ob_hash_engine.h \
    src/updateserver/ob_inc_seq.h \
    src/updateserver/ob_lighty_hash.h \
    src/updateserver/ob_located_log_reader.h \
    src/updateserver/ob_lock_mgr.h \
    src/updateserver/ob_log_buffer.h \
    src/updateserver/ob_log_locator.h \
    src/updateserver/ob_log_replay_worker.h \
    src/updateserver/ob_log_src.h \
    src/updateserver/ob_log_sync_delay_stat.h \
    src/updateserver/ob_memtable_modify.h \
    src/updateserver/ob_memtable_rowiter.h \
    src/updateserver/ob_memtable.h \
    src/updateserver/ob_memtank.h \
    src/updateserver/ob_multi_file_utils.h \
    src/updateserver/ob_obi_slave_stat.h \
    src/updateserver/ob_on_disk_log_locator.h \
    src/updateserver/ob_pos_log_reader.h \
    src/updateserver/ob_prefetch_log_buffer.h \
    src/updateserver/ob_query_engine.h \
    src/updateserver/ob_recent_cache.h \
    src/updateserver/ob_remote_log_src.h \
    src/updateserver/ob_replay_log_src.h \
    src/updateserver/ob_ring_data_buffer.h \
    src/updateserver/ob_schema_mgr.h \
    src/updateserver/ob_schema_mgrv2.h \
    src/updateserver/ob_session_guard.h \
    src/updateserver/ob_session_mgr.h \
    src/updateserver/ob_sessionctx_factory.h \
    src/updateserver/ob_slave_sync_type.h \
    src/updateserver/ob_sstable_mgr.h \
    src/updateserver/ob_store_mgr.h \
    src/updateserver/ob_table_engine.h \
    src/updateserver/ob_table_list_query.h \
    src/updateserver/ob_table_mgr.h \
    src/updateserver/ob_trans_buffer.h \
    src/updateserver/ob_trans_executor.h \
    src/updateserver/ob_trans_mgr.h \
    src/updateserver/ob_transfer_sstable_query.h \
    src/updateserver/ob_trigger_handler.h \
    src/updateserver/ob_update_callback.h \
    src/updateserver/ob_update_reload_config.h \
    src/updateserver/ob_update_server_config.h \
    src/updateserver/ob_update_server_main.h \
    src/updateserver/ob_update_server.h \
    src/updateserver/ob_ups_cache.h \
    src/updateserver/ob_ups_check_runnable.h \
    src/updateserver/ob_ups_clog_status.h \
    src/updateserver/ob_ups_compact_cell_iterator.h \
    src/updateserver/ob_ups_compact_cell_writer.h \
    src/updateserver/ob_ups_fetch_lsync.h \
    src/updateserver/ob_ups_fetch_runnable.h \
    src/updateserver/ob_ups_inc_scan.h \
    src/updateserver/ob_ups_keep_alive.h \
    src/updateserver/ob_ups_lease_task.h \
    src/updateserver/ob_ups_lock_filter.h \
    src/updateserver/ob_ups_log_mgr.h \
    src/updateserver/ob_ups_log_utils.h \
    src/updateserver/ob_ups_mutator.h \
    src/updateserver/ob_ups_phy_operator_factory.h \
    src/updateserver/ob_ups_replay_runnable.h \
    src/updateserver/ob_ups_role_mgr.h \
    src/updateserver/ob_ups_rpc_proxy.h \
    src/updateserver/ob_ups_rpc_stub.h \
    src/updateserver/ob_ups_slave_mgr.h \
    src/updateserver/ob_ups_stat.h \
    src/updateserver/ob_ups_table_mgr.h \
    src/updateserver/ob_ups_timer_task.h \
    src/updateserver/ob_ups_tmps.h \
    src/updateserver/ob_ups_utils.h \
    src/updateserver/ob_util_interface.h \
    src/updateserver/stress.h \
    src/updateserver/ups_mon.h \
    src/compactsstable/ob_block_membuf.h \
    src/compactsstable/ob_compact_obj.h \
    src/compactsstable/ob_compact_row.h \
    src/compactsstable/ob_compactsstable_mem.h

SOURCES += \
   src/chunkserver/main.cpp \
   src/chunkserver/ob_block_cache_loader.cpp \
   src/chunkserver/ob_block_cache_reader.cpp \
   src/chunkserver/ob_bypass_sstable_loader.cpp \
   src/chunkserver/ob_cell_array_helper.cpp \
   src/chunkserver/ob_cell_stream.cpp \
   src/chunkserver/ob_chunk_callback.cpp \
   src/chunkserver/ob_chunk_merge.cpp \
   src/chunkserver/ob_chunk_reload_config.cpp \
   src/chunkserver/ob_chunk_server_config.cpp \
   src/chunkserver/ob_chunk_server_main.cpp \
   src/chunkserver/ob_chunk_server_merger_proxy.cpp \
   src/chunkserver/ob_chunk_server_stat.cpp \
   src/chunkserver/ob_chunk_server.cpp \
   src/chunkserver/ob_chunk_service.cpp \
   src/chunkserver/ob_compactsstable_cache.cpp \
   src/chunkserver/ob_disk_manager.cpp \
   src/chunkserver/ob_disk_path.cpp \
   src/chunkserver/ob_file_recycle.cpp \
   src/chunkserver/ob_fileinfo_cache.cpp \
   src/chunkserver/ob_get_cell_stream_wrapper.cpp \
   src/chunkserver/ob_get_cell_stream.cpp \
   src/chunkserver/ob_get_param_cell_iterator.cpp \
   src/chunkserver/ob_get_scan_proxy.cpp \
   src/chunkserver/ob_join_cache.cpp \
   src/chunkserver/ob_join_operator.cpp \
   src/chunkserver/ob_merge_join_operator.cpp \
   src/chunkserver/ob_merge_operator.cpp \
   src/chunkserver/ob_merge_reader.cpp \
   src/chunkserver/ob_multi_tablet_merger.cpp \
   src/chunkserver/ob_query_agent.cpp \
   src/chunkserver/ob_query_service.cpp \
   src/chunkserver/ob_read_param_modifier.cpp \
   src/chunkserver/ob_read_ups_balance.cpp \
   src/chunkserver/ob_root_server_rpc.cpp \
   src/chunkserver/ob_row_cell_vec.cpp \
   src/chunkserver/ob_rpc_proxy.cpp \
   src/chunkserver/ob_scan_cell_stream.cpp \
   src/chunkserver/ob_schema_manager.cpp \
   src/chunkserver/ob_schema_task.cpp \
   src/chunkserver/ob_sql_rpc_stub.cpp \
   src/chunkserver/ob_switch_cache_utility.cpp \
   src/chunkserver/ob_tablet_image.cpp \
   src/chunkserver/ob_tablet_manager.cpp \
   src/chunkserver/ob_tablet_merge_filter.cpp \
   src/chunkserver/ob_tablet_merger_v1.cpp \
   src/chunkserver/ob_tablet_merger_v2.cpp \
   src/chunkserver/ob_tablet_reader.cpp \
   src/chunkserver/ob_tablet_service.cpp \
   src/chunkserver/ob_tablet_writer.cpp \
   src/chunkserver/ob_tablet.cpp \
   src/chunkserver/ob_ups_blacklist.cpp \
   src/clustermanager/ob_ocm_app_info.cpp \
   src/clustermanager/ob_ocm_broadcast_task.cpp \
   src/clustermanager/ob_ocm_instance.cpp \
   src/clustermanager/ob_ocm_main.cpp \
   src/clustermanager/ob_ocm_meta_manager.cpp \
   src/clustermanager/ob_ocm_meta.cpp \
   src/clustermanager/ob_ocm_param.cpp \
   src/clustermanager/ob_ocm_rpc_stub.cpp \
   src/clustermanager/ob_ocm_server.cpp \
   src/clustermanager/ob_ocm_service.cpp \
   src/clustermanager/ocm_admin.cpp \
   src/common/btree/test/btree_alloc_test.cpp \
   src/common/btree/test/btree_base_test.cpp \
   src/common/btree/test/btree_node_test.cpp \
   src/common/btree/test/btree_read_handle_test.cpp \
   src/common/btree/test/btree_root_pointer_test.cpp \
   src/common/btree/test/btree_test.cpp \
   src/common/btree/test/btree_write_handle_test.cpp \
   src/common/btree/test/key_btree_mthread.cpp \
   src/common/btree/test/key_btree_test.cpp \
   src/common/btree/test/keytree_get_test.cpp \
   src/common/btree/test/keytree_getnext_test.cpp \
   src/common/btree/test/keytree_put_test.cpp \
   src/common/btree/test/keytree_remove_test.cpp \
   src/common/btree/test/test_batch.cpp \
   src/common/* \
   src/common/cmbtree/test.cpp \
   src/common/cmbtree/test1.cpp \
   src/common/cmbtree/test2.cpp \
   src/common/cmbtree/test3.cpp \
   src/common/cmbtree/test4.cpp \
   src/common/compress/lzo_compressor.cpp \
   src/common/compress/none_compressor.cpp \
   src/common/compress/ob_compressor.cpp \
   src/common/compress/snappy_compressor.cpp \
   src/common/location/ob_tablet_location_cache_proxy.cpp \
   src/common/location/ob_tablet_location_cache.cpp \
   src/common/location/ob_tablet_location_list.cpp \
   src/common/location/ob_tablet_location_range_iterator.cpp \
   src/common/nb_accessor/nb_query_res.cpp \
   src/common/nb_accessor/nb_scan_cond.cpp \
   src/common/nb_accessor/nb_table_row.cpp \
   src/common/nb_accessor/ob_nb_accessor.cpp \
   src/common/roottable/ob_first_tablet_entry_meta.cpp \
   src/common/roottable/ob_first_tablet_entry_schema.cpp \
   src/common/roottable/ob_first_tablet_entry.cpp \
   src/common/roottable/ob_meta_table_schema.cpp \
   src/common/roottable/ob_meta_table3.cpp \
   src/common/roottable/ob_old_root_table_schema.cpp \
   src/common/roottable/ob_root_table_service.cpp \
   src/common/roottable/ob_root_table3.cpp \
   src/common/roottable/ob_scan_helper_impl.cpp \
   src/common/roottable/ob_tablet_meta_table_row.cpp \
   src/common/timezone/localtime.c \
    src/mergeserver/main.cpp \
    src/mergeserver/ob_bloom_filter_task_queue_thread.cpp \
    src/mergeserver/ob_chunk_server_task_dispatcher.cpp \
    src/mergeserver/ob_frozen_data_cache.cpp \
    src/mergeserver/ob_get_privilege_task.cpp \
    src/mergeserver/ob_insert_cache.cpp \
    src/mergeserver/ob_merge_callback.cpp \
    src/mergeserver/ob_merge_reload_config.cpp \
    src/mergeserver/ob_merge_server_config.cpp \
    src/mergeserver/ob_merge_server_main.cpp \
    src/mergeserver/ob_merge_server_service.cpp \
    src/mergeserver/ob_merge_server.cpp \
    src/mergeserver/ob_merger_groupby_operator.cpp \
    src/mergeserver/ob_merger_operator.cpp \
    src/mergeserver/ob_merger_reverse_operator.cpp \
    src/mergeserver/ob_merger_sorted_operator.cpp \
    src/mergeserver/ob_ms_async_rpc.cpp \
    src/mergeserver/ob_ms_dump_util.cpp \
    src/mergeserver/ob_ms_get_request.cpp \
    src/mergeserver/ob_ms_lease_task.cpp \
    src/mergeserver/ob_ms_monitor_task.cpp \
    src/mergeserver/ob_ms_request.cpp \
    src/mergeserver/ob_ms_rpc_event.cpp \
    src/mergeserver/ob_ms_rpc_proxy.cpp \
    src/mergeserver/ob_ms_scan_param.cpp \
    src/mergeserver/ob_ms_scan_request.cpp \
    src/mergeserver/ob_ms_scanner_encoder.cpp \
    src/mergeserver/ob_ms_schema_proxy.cpp \
    src/mergeserver/ob_ms_schema_task.cpp \
    src/mergeserver/ob_ms_server_counter.cpp \
    src/mergeserver/ob_ms_service_monitor.cpp \
    src/mergeserver/ob_ms_sql_get_request.cpp \
    src/mergeserver/ob_ms_sql_operator.cpp \
    src/mergeserver/ob_ms_sql_proxy.cpp \
    src/mergeserver/ob_ms_sql_request.cpp \
    src/mergeserver/ob_ms_sql_rpc_event.cpp \
    src/mergeserver/ob_ms_sql_scan_request.cpp \
    src/mergeserver/ob_ms_sql_sorted_operator.cpp \
    src/mergeserver/ob_ms_sql_sub_get_request.cpp \
    src/mergeserver/ob_ms_sql_sub_scan_request.cpp \
    src/mergeserver/ob_ms_sub_get_request.cpp \
    src/mergeserver/ob_ms_sub_scan_request.cpp \
    src/mergeserver/ob_ms_ups_task.cpp \
    src/mergeserver/ob_mutator_param_decoder.cpp \
    src/mergeserver/ob_param_decoder.cpp \
    src/mergeserver/ob_query_cache.cpp \
    src/mergeserver/ob_read_param_decoder.cpp \
    src/mergeserver/ob_read_param_modifier.cpp \
    src/mergeserver/ob_rpc_event.cpp \
    src/mergeserver/ob_rs_rpc_proxy.cpp \
    src/mergeserver/ob_sql_rpc_event.cpp \
    src/rootserver/main.cpp \
    src/rootserver/ob_check_point2str.cpp \
    src/rootserver/ob_chunk_server_manager.cpp \
    src/rootserver/ob_clist2str.cpp \
    src/rootserver/ob_daily_merge_checker.cpp \
    src/rootserver/ob_data_source_mgr.cpp \
    src/rootserver/ob_heartbeat_checker.cpp \
    src/rootserver/ob_migrate_info.cpp \
    src/rootserver/ob_restart_server.cpp \
    src/rootserver/ob_root_admin2_main.cpp \
    src/rootserver/ob_root_admin2.cpp \
    src/rootserver/ob_root_async_task_queue.cpp \
    src/rootserver/ob_root_balancer_runnable.cpp \
    src/rootserver/ob_root_balancer.cpp \
    src/rootserver/ob_root_bootstrap.cpp \
    src/rootserver/ob_root_callback.cpp \
    src/rootserver/ob_root_ddl_operator.cpp \
    src/rootserver/ob_root_fetch_thread.cpp \
    src/rootserver/ob_root_inner_table_task.cpp \
    src/rootserver/ob_root_log_manager.cpp \
    src/rootserver/ob_root_log_replay.cpp \
    src/rootserver/ob_root_log_worker.cpp \
    src/rootserver/ob_root_main.cpp \
    src/rootserver/ob_root_meta2.cpp \
    src/rootserver/ob_root_monitor_table.cpp \
    src/rootserver/ob_root_ms_provider.cpp \
    src/rootserver/ob_root_operation_data.cpp \
    src/rootserver/ob_root_operation_helper.cpp \
    src/rootserver/ob_root_reload_config.cpp \
    src/rootserver/ob_root_rpc_stub.cpp \
    src/rootserver/ob_root_server_config.cpp \
    src/rootserver/ob_root_server_state.cpp \
    src/rootserver/ob_root_server2.cpp \
    src/rootserver/ob_root_sql_proxy.cpp \
    src/rootserver/ob_root_stat_key.cpp \
    src/rootserver/ob_root_table_operation.cpp \
    src/rootserver/ob_root_table2.cpp \
    src/rootserver/ob_root_timer_task.cpp \
    src/rootserver/ob_root_ups_provider.cpp \
    src/rootserver/ob_root_util.cpp \
    src/rootserver/ob_root_worker.cpp \
    src/rootserver/ob_rs_after_restart_task.cpp \
    src/rootserver/ob_rs_schema_operation.cpp \
    src/rootserver/ob_rs_stress.cpp \
    src/rootserver/ob_rs_trigger_event_util.cpp \
    src/rootserver/ob_schema_reader.cpp \
    src/rootserver/ob_schema_service_ms_provider.cpp \
    src/rootserver/ob_schema_service_ups_provider.cpp \
    src/rootserver/ob_server_balance_info.cpp \
    src/rootserver/ob_str2check_point.cpp \
    src/rootserver/ob_tablet_info_manager.cpp \
    src/rootserver/ob_ups_check_runnable.cpp \
    src/rootserver/ob_ups_heartbeat_runnable.cpp \
    src/rootserver/ob_ups_manager.cpp \
    src/proxyserver/main.cpp \
    src/proxyserver/ob_proxy_callback.cpp \
    src/proxyserver/ob_proxy_reader.cpp \
    src/proxyserver/ob_proxy_server_config.cpp \
    src/proxyserver/ob_proxy_server_main.cpp \
    src/proxyserver/ob_proxy_server.cpp \
    src/proxyserver/ob_proxy_service.cpp \
    src/proxyserver/ob_yunti_meta.cpp \
    src/proxyserver/ob_yunti_proxy.cpp \
    src/updateserver/main.cpp \
    src/updateserver/ob_async_log_applier.cpp \
    src/updateserver/ob_btree_engine_alloc.cpp \
    src/updateserver/ob_btree_engine.cpp \
    src/updateserver/ob_cached_pos_log_reader.cpp \
    src/updateserver/ob_client_wrapper.cpp \
    src/updateserver/ob_clog_stat.cpp \
    src/updateserver/ob_commit_log_receiver.cpp \
    src/updateserver/ob_data_block.cpp \
    src/updateserver/ob_fetched_log.cpp \
    src/updateserver/ob_hash_engine.cpp \
    src/updateserver/ob_inc_seq.cpp \
    src/updateserver/ob_located_log_reader.cpp \
    src/updateserver/ob_lock_mgr.cpp \
    src/updateserver/ob_log_buffer.cpp \
    src/updateserver/ob_log_replay_worker.cpp \
    src/updateserver/ob_log_src.cpp \
    src/updateserver/ob_log_sync_delay_stat.cpp \
    src/updateserver/ob_memtable_modify.cpp \
    src/updateserver/ob_memtable_rowiter.cpp \
    src/updateserver/ob_memtable.cpp \
    src/updateserver/ob_multi_file_utils.cpp \
    src/updateserver/ob_on_disk_log_locator.cpp \
    src/updateserver/ob_pos_log_reader.cpp \
    src/updateserver/ob_prefetch_log_buffer.cpp \
    src/updateserver/ob_query_engine.cpp \
    src/updateserver/ob_remote_log_src.cpp \
    src/updateserver/ob_replay_log_src.cpp \
    src/updateserver/ob_ring_data_buffer.cpp \
    src/updateserver/ob_schema_mgr.cpp \
    src/updateserver/ob_schema_mgrv2.cpp \
    src/updateserver/ob_session_mgr.cpp \
    src/updateserver/ob_sessionctx_factory.cpp \
    src/updateserver/ob_slave_sync_type.cpp \
    src/updateserver/ob_sstable_mgr.cpp \
    src/updateserver/ob_store_mgr.cpp \
    src/updateserver/ob_table_engine.cpp \
    src/updateserver/ob_table_list_query.cpp \
    src/updateserver/ob_table_mgr.cpp \
    src/updateserver/ob_trans_buffer.cpp \
    src/updateserver/ob_trans_executor.cpp \
    src/updateserver/ob_trans_mgr.cpp \
    src/updateserver/ob_transfer_sstable_query.cpp \
    src/updateserver/ob_trigger_handler.cpp \
    src/updateserver/ob_update_callback.cpp \
    src/updateserver/ob_update_reload_config.cpp \
    src/updateserver/ob_update_server_config.cpp \
    src/updateserver/ob_update_server_main.cpp \
    src/updateserver/ob_update_server.cpp \
    src/updateserver/ob_ups_cache.cpp \
    src/updateserver/ob_ups_check_runnable.cpp \
    src/updateserver/ob_ups_clog_status.cpp \
    src/updateserver/ob_ups_compact_cell_iterator.cpp \
    src/updateserver/ob_ups_compact_cell_writer.cpp \
    src/updateserver/ob_ups_fetch_lsync.cpp \
    src/updateserver/ob_ups_fetch_runnable.cpp \
    src/updateserver/ob_ups_inc_scan.cpp \
    src/updateserver/ob_ups_keep_alive.cpp \
    src/updateserver/ob_ups_lease_task.cpp \
    src/updateserver/ob_ups_lock_filter.cpp \
    src/updateserver/ob_ups_log_mgr.cpp \
    src/updateserver/ob_ups_log_utils.cpp \
    src/updateserver/ob_ups_mutator.cpp \
    src/updateserver/ob_ups_phy_operator_factory.cpp \
    src/updateserver/ob_ups_replay_runnable.cpp \
    src/updateserver/ob_ups_rpc_proxy.cpp \
    src/updateserver/ob_ups_rpc_stub.cpp \
    src/updateserver/ob_ups_slave_mgr.cpp \
    src/updateserver/ob_ups_stat.cpp \
    src/updateserver/ob_ups_table_mgr.cpp \
    src/updateserver/ob_ups_timer_task.cpp \
    src/updateserver/ob_ups_utils.cpp \
    src/updateserver/ups_mon.cpp \
    src/compactsstable/ob_block_membuf.cpp \
    src/compactsstable/ob_compact_row.cpp \
    src/compactsstable/ob_compactsstable_mem.cpp

